production:
  adapter: mysql2
  host: <%= ENV["REDMINE_DATABASE_HOST"] %>
  database: <%= ENV["REDMINE_DATABASE_NAME"] %>
  username: <%= ENV["REDMINE_DATABASE_USERNAME"] %>
  password: <%= ENV["REDMINE_DATABASE_PASSWORD"] %>
  encoding: <%= ENV["REDMINE_DATABASE_ENCODING"] %>