production:
  adapter: mysql2
  host: __REDMINE_DATABASE_HOST__
  database: __REDMINE_DATABASE_NAME__
  username: __REDMINE_DATABASE_USERNAME__
  password: __REDMINE_DATABASE_PASSWORD__
  encoding: __REDMINE_DATABASE_ENCODING__